version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "Hello, CircleCI!"

orbs:
  jira: circleci/jira@1.3.1

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                project_key: TS
                issue_type: Task
                summary: CircleCI Build Status
                description: >
                  CircleCI Build has completed for $CIRCLE_PROJECT_REPONAME.
                  Status: $CIRCLE_JOB
                  Commit: $CIRCLE_SHA1
                  Build URL: $CIRCLE_BUILD_URL
